@baseUrl = http://localhost:3333
@authToken = {{authenticate_session.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/account
Content-Type: application/json

{
  "name": "Joe Doe",
  "email": "joedoe2@email.com",
  "password": "123456"
}

###

# @name authenticate_session

POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "joedoe2@email.com",
  "password": "123456"
}

###

# @name create_question

POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova Pergunta 1",
  "content": "Esta é uma pergunta de teste 1"
}

###

# @name fetch_recent_questions

GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_recent_questions_pagination

GET {{baseUrl}}/questions?page=2
Content-Type: application/json
Authorization: Bearer {{authToken}}


